### ISSUE TITLE
Bug - Items dissapear

### ISSUE THREAD

**Issue by matipoirierg** [CodedRed-Spigot/SafeDrop#2]
https://user-images.githubusercontent.com/97362850/222193198-8c2f9877-13f8-4ee9-8d13-711073235648.mp4

**Comment by CodedRedGIT** [comment]
Thanks for reporting, will fix asap.

**Comment by CodedRedGIT** [comment]
Plugin updated with fixes. Thanks again.

https://www.spigotmc.org/resources/safedrop-safely-drop-items.72585/
